### ISSUE TITLE
Badge support

### ISSUE THREAD

**Issue by PeterShaws** [Gruntfuggly/activitusbar#53]
It would be nice not to lose the information from the Activity Bar badges. One possible implementation could look like the mockup below:

![Activitus Bar with badges](https://i.imgur.com/8Wh3MMc.png)

Would that be feasible?

**Comment by PeterShaws** [comment]
I just saw the **wontfix** on issue #37. Is that still the case?

**Comment by Gruntfuggly** [comment]
If you set `activitusbar.showSourceControlCounter` to true, it should show a number for the SCM view, but the others are not possible to do.

**Comment by PeterShaws** [comment]
That's unfortunate. I did find and enable that option, but the counter didn't appear, even after reloading the window.

**Comment by Gruntfuggly** [comment]
Could you have look in the developer tool console (Help->Toggle Developer Tools) and see if there are any errors present?

**Comment by PeterShaws** [comment]
Indeed there is:

```
log.ts:313   ERR [Extension Host] The system cannot find the path specified.
console.ts:137 [Extension Host] The system cannot find the path specified.
console.ts:137 [Extension Host] Settings Cycler: Log level 1
localProcessExtensionHost.ts:294 Extension Host
localProcessExtensionHost.ts:295 The system cannot find the path specified.
```

**Comment by Gruntfuggly** [comment]
Hmm. Unfortunately that doesn't give me much to go on - was there anything else?

**Comment by PeterShaws** [comment]
Yeah, I thought the same, but I can't make heads or tails of the trace for the `ExtensionHost` error:

```
log.ts:313   ERR [Extension Host] The system cannot find the path specified.
console.ts:137 [Extension Host] The system cannot find the path specified.
I @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:473
_invokeHandler @ rpcProtocol.ts:458
_receiveRequest @ rpcProtocol.ts:374
_receiveOneMessage @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:569
fire @ event.ts:736
fire @ ipc.net.ts:638
_receiveMessage @ ipc.net.ts:958
(anonymous) @ ipc.net.ts:831
invoke @ event.ts:569
fire @ event.ts:736
acceptChunk @ ipc.net.ts:382
(anonymous) @ ipc.net.ts:338
B @ ipc.net.ts:60
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
console.ts:137 [Extension Host] Settings Cycler: Log level 1
localProcessExtensionHost.ts:294 Extension Host
localProcessExtensionHost.ts:295 The system cannot find the path specified.
```

**Comment by cesarionivar** [comment]
Hey, I'm having the same problem. 

The SCM badge in Linux works perfectly, but  in Windows, it doesn't; In the Developer Tools it throws  the error 
> The system cannot find the path specified.

I think the problem could be in the `folder.uri.fsPath`

https://github.com/Gruntfuggly/activitusbar/blob/3927c24f90b0168bfa2fd6a22dd550afc50b09be/extension.js#L420

**Comment by mikebronner** [comment]
I'm not seeing the "SCM changes" badge either, this is on macOS Ventura, also don't see any errors in the developer console. Here are my settings:

```yml
    "activitusbar.combineWorkspaceSettings": true,
    "activitusbar.searchViewInPanel": false,
    "activitusbar.showSourceControlCounter": true,
    "activitusbar.views": [
        {
            "name": "explorer",
            "codicon": "explorer-view-icon"
        },
        {
            "name": "search",
            "codicon": "search-view-icon"
        },
        {
            "name": "pr:github",
            "codicon": "github"
        },
        {
            "name": "scm",
            "codicon": "source-control-view-icon"
        },
        {
            "name": "debug",
            "codicon": "run-view-icon"
        },
        {
            "name": "github.codespaces.explorer",
            "codicon": "remote-explorer"
        },
        {
            "name": "gitlens.views.home",
            "codicon": "git-merge"
        },
        {
            "name": "extensions",
            "codicon": "extensions-view-icon"
        },
        {
            "codicon": "kebab-vertical"
        }
    ],

```
